name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 0: setup .env
      - name: Create .env File
        run: |
          touch .env
          echo "POSTGRES_USER=admin" >> .env
          echo "POSTGRES_PASSWORD=admin123" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=admin123" >> .env
          echo "PGADMIN_CONNECTION_URI=postgresql://admin:admin123@postgres:5432/postgres" >> .env
          echo "PGADMIN_PORT=8080" >> .env
          echo "SERVICE_PORT=5000" >> .env
          echo "POSTGRES_HOST=localhost" >> .env
          cat .env
          ls -a
      
