name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub (optional, if pushing images)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and run Docker Compose
    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d

    # Step 5: Run tests (optional)
    - name: Run tests
      run: |
        docker-compose exec app npm test  # Replace 'app' with your service name

    # Step 6: Tear down services after tests (optional)
    - name: Tear down Docker Compose
      if: always()
      run: |
        docker-compose down
