name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env File
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env
