name: CI/CD with Docker Compose

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # LOGIN
      - name: Login Docker
        run: echo ${{ secrets.D_PASSWORD }} | docker login ghcr.io -u ${{ secrets.D_NAME }} --password-stdin

      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.D_NAME }}
      #     password: ${{ secrets.D_PASSWORD }}

      # Check out the code   
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .env
      - name: Create .env File
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" >> .env
          cat .env
      
      - name: Set image tag
        run: echo "IMAGE_TAG=ghcr.io/czer0c/short-link2/your-image:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_TAG }}
    #   # Step 2: Set up Docker
    #   - name: Set up Docker
    #     uses: docker/setup-buildx-action@v2

    #   # Step 3: Install Docker Compose
    #   - name: Install Docker Compose
    #     run: |
    #       sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #       sudo chmod +x /usr/local/bin/docker-compose
    #   # Step 4: Verify Docker Compose Installation
    #   - name: Check Docker Compose version
    #     run: docker-compose --version
    #   # Step 0: setup .env
    #   - name: Create .env File
    #     run: |
    #       touch .env
    #       echo "${{ secrets.ENV_FILE }}" >> .env
    #       cat .env
    #   # Step 4: Verify Docker Compose Installation
    #   - name: CHECK FILES
    #     run: ls -a
    #   # Step 5: Build and run Docker Compose
    #   - name: Build and run Docker Compose
    #     run: docker-compose up --build -d

    #   # Step 6: Tear down Docker Compose
    #   - name: Tear down Docker Compose
    #     if: always()
    #     run: docker-compose down
